model_name: "llama3"
batch_size: 4
dataset_path: "src/preprocess/data/"
test_data: "lm-critical-period/data/babylm_2024/en/raw/test.txt"
summary_output_path: "src/probabilities/results/llama3"
huggingface_cache_dir: "/cluster/scratch/fficarra"
